name: Validate windows runner

on:
  push:

env:
  DOCKER_REGISTRY: "docker.io"
  DOCKER_BUILDKIT: 1
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  WITH_PUSH: ${{ github.event_name == 'push' }}

jobs:
  validate-windows-runner:
    runs-on: windows-nvidia-m60
    timeout-minutes: 60
#    strategy:
#      matrix:
#        cuda_version: ["116"]
#        python_version: ["3.8"]
    env:
      CUDA_VERSION: "116"
#      GPU_ARCH_TYPE: cuda
#      GPU_ARCH_VERSION: ${{ matrix.cuda_version }}
#      PYTHON_VERSION: ${{ matrix.python_version }}
    steps:
      - name: Checkout PyTorch builder
        uses: actions/checkout@v2
#      - uses: msys2/setup-msys2@v2
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
#        with:
#          sudo: false
#      - name: Install 7-zip
#        run: windows/internal/7z_install.bat
#      - name: Install CUDA Toolkit
#        run: windows/internal/cuda_install.bat
      - name: Install driver
        run: windows/internal/driver_update.bat
      - name: Check nvidia smi
        run: |
          nvidia-smi