name: Validate windows runner

on:
  push:

env:
  DOCKER_REGISTRY: "docker.io"
  DOCKER_BUILDKIT: 1
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  WITH_PUSH: ${{ github.event_name == 'push' }}

jobs:
  validate-windows-runner:
    runs-on: windows-nvidia-m60
#    strategy:
#      matrix:
#        cuda_version: ["116"]
#        python_version: ["3.8"]
    env:
      CUDA_VERSION: "116"
#      GPU_ARCH_TYPE: cuda
#      GPU_ARCH_VERSION: ${{ matrix.cuda_version }}
#      PYTHON_VERSION: ${{ matrix.python_version }}
    steps:
      - name: Checkout PyTorch builder
        uses: actions/checkout@v2
#      - name: Enable MSVC dev commands to enable cl.exe  # FYI incompatible with shell: bash
#        uses: ilammy/msvc-dev-cmd@dd5e2fa0a7de1e7929605d9ecc020e749d9856a3
      - name: Install CUDA Toolkit
        run: windows/internal/cuda_install.bat
      - name: Check nvidia smi
        run: |
          nvidia-smi